
services:
  oracle-db:
    image: gvenzl/oracle-xe:21-slim
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: password
    volumes:
      - ./init:/container-entrypoint-initdb.d

